function A_m = Am_tmp(l1,l2,l3,m,q1_m,q2_m,q3_m)
%AM_TMP
%    A_M = AM_TMP(L1,L2,L3,M,Q1_M,Q2_M,Q3_M)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    31-Oct-2018 17:56:20

t2 = q1_m+q2_m;
t3 = cos(t2);
t4 = q1_m+q3_m;
t5 = cos(t4);
t6 = l1.*l3.*t5.*2.0;
t7 = l1.^2;
t8 = l3.^2;
t9 = t6+t8;
A_m = reshape([m.*(t6+t7.*9.0-l1.*l2.*t3.*2.0).*(1.0./4.0),0.0,m.*(t6+t7.*4.0).*(1.0./2.0),m.*(l2.^2-l1.*l2.*t3.*2.0).*(-1.0./4.0),0.0,0.0,m.*t9.*(-1.0./4.0),0.0,m.*t9.*(-1.0./2.0)],[3,3]);
