function A_p = Ap_tmp(l1,l2,l3,m,q1_p,q2_p,q3_p)
%AP_TMP
%    A_P = AP_TMP(L1,L2,L3,M,Q1_P,Q2_P,Q3_P)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Nov-2018 17:14:50

t2 = q1_p-q2_p;
t3 = cos(t2);
t4 = q1_p-q3_p;
t5 = cos(t4);
t6 = l3.^2;
A_p = reshape([m.*(l1.^2.*5.0-l1.*l2.*t3.*2.0+l1.*l3.*t5.*2.0).*(-1.0./4.0),l1.*l2.*m.*t3,-l1.*l3.*m.*t5,m.*(l2.^2-l1.*l2.*t3.*2.0).*(-1.0./4.0),0.0,0.0,m.*t6.*(-1.0./4.0),0.0,m.*t6.*(-1.0./2.0)],[3,3]);
