function A_p = Ap_tmp(l1,l2,l3,m,q1,q1_p,q2_p,q3_p)
%AP_TMP
%    A_P = AP_TMP(L1,L2,L3,M,Q1,Q1_P,Q2_P,Q3_P)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    31-Oct-2018 17:56:20

t2 = l1.^2;
t3 = q1_p+q2_p;
t4 = cos(t3);
t5 = q1_p+q3_p;
t6 = cos(t5);
t7 = l1.*l3.*t6.*2.0;
t8 = cos(q1_p);
t9 = sin(q1_p);
t10 = cos(q3_p);
t11 = cos(q1);
t12 = l1.*t8;
t13 = l3.*t10.*(1.0./2.0);
t14 = t12+t13-l1.*t11;
t15 = sin(q3_p);
t16 = sin(q1);
t17 = l1.*t16;
t18 = l3.*t15.*(1.0./2.0);
t19 = t17+t18-l1.*t9;
A_p = reshape([m.*(t2.*9.0+t7-t2.*cos(q1-q1_p).*4.0-l1.*l2.*t4.*2.0).*(1.0./4.0),0.0,l1.*m.*t8.*t14.*2.0-l1.*m.*t9.*t19.*2.0,m.*(l2.^2-l1.*l2.*t4.*2.0).*(-1.0./4.0),0.0,0.0,m.*(t7+l3.^2-l1.*l3.*cos(q1+q3_p).*2.0).*(-1.0./4.0),0.0,-l3.*m.*t10.*t14-l3.*m.*t15.*t19],[3,3]);
